### ISSUE TITLE
Bad underlining, suggestions for double-space err after misspelling

### ISSUE THREAD

**Issue by snomos** [divvun/libdivvun#31] opened 2019-08-14 06:42 UTC
[This bug could also be caused by the CG rules, but I am posting it here to begin with]

Given the command (there should be two spaces after the first word of the input sentence):

> `echo "Riggeroahkká  lea gitta suomuoras, ja vuohkui mii heaŋga vuolimuš sáhttá bidjat gáfegievnni dahje málesgievnni." | tools/grammarcheckers/modes/trace-smegramrelease.mode`

one gets the following output:

```
"<Riggeroahkká>"
	"reahkká" N Sem/Ani Sg Nom <W:37.3018> <WA:17.3018> <spelled> "<diggereahkká>" PROTECT:3268 SELECT:3578:r868 &double-space-before ID:1 ADD:4001:double-space-before-link ADD:4033:spelled
		"diggi" N Sem/Org Cmp/SgNom Cmp ID:1
double-space-before
	"reahkká" N Sem/Ani Sg Nom <W:37.3018> <WA:17.3018> <spelled> "<diggereahkká>" PROTECT:3268 SELECT:3578:r868 &LINK &typo &SUGGESTWF ID:1 ADD:4001:double-space-before-link ADDRELATION($2):4002:double-space-before-rel ADDRELATION(LEFT):4003:double-space-before-rel ADD:4033:spelled
		"diggi" N Sem/Org Cmp/SgNom Cmp ID:1
typo
	"roahkki" N Sem/Dummytag Sg Nom <W:37.3018> <WA:17.3018> <spelled> "<diggeroahkki>" PROTECT:3268 SELECT:3578:r868 &LINK &double-space-before &typo &SUGGESTWF ID:1 ADD:4001:double-space-before-link ADD:4033:spelled
		"diggi" N Sem/Org Cmp/SgNom Cmp ID:1
double-space-before
typo
...
;	"Riggeroahkká" ? SELECT:3578:r868
:  
"<lea>"
	"leat" V <TH-Nom-Any> <mielde> <OR-Loc-HumGroup> <OR-eret-Plc> <dušše><TH-Inf> <árvvus> <LO-Loc-johtu><DE-Ill-Plc> <AT-Loc-Mat> <AT-Abe-Any> <AT-Nom-Any> <AT-Nom-Adj><EX-Ill-Ani> <PO-Loc-Hum> <PO-Gen-Hum> <MA-mielde-Any> <MA-Adv-Manner> <XT-Gen-Measr> <LO-maŋŋil-Time> <LO-Acc-Time> <LO-Loc-Time> <CO-Com-Ani> <ID-Nom-Any> <TH-Nom-Any><RO-Ess-Any><EX-Ill-Any> <EX-Ill-Ani><TH-Nom-Adj> <EX-Ill-Ani> <TH-Nom-Obj><RE-Ill-Ani> <LO-Loc-Any> <AktioEss> <BE-Ill-Ani><PU-Ess-Any> <RO-Ess-Any><PU-Ill-Act> <RO-Ess-Any> IV Ind Prs Sg3 <W:0.0> <doubleSpaceBefore> SUBSTITUTE:2764 SUBSTITUTE:2772 SUBSTITUTE:2979 SUBSTITUTE:3083 SUBSTITUTE:3121 SUBSTITUTE:3494 SUBSTITUTE:3593 SUBSTITUTE:3598 SUBSTITUTE:3605 SUBSTITUTE:3616 SUBSTITUTE:3704 SUBSTITUTE:3834 SUBSTITUTE:3845 SUBSTITUTE:3849 SUBSTITUTE:3999 SUBSTITUTE:4158 SUBSTITUTE:4169 SUBSTITUTE:4281 SUBSTITUTE:4286 SUBSTITUTE:4299 SUBSTITUTE:4306 SUBSTITUTE:4312 SUBSTITUTE:4539 SUBSTITUTE:4637 SUBSTITUTE:4698 SUBSTITUTE:4721 SUBSTITUTE:4727 SUBSTITUTE:4759 SUBSTITUTE:4875 @+FMAINV MAP:15822 &double-space-before ID:2 R:$2:1 R:LEFT:1 ADD:4000:double-space-before
double-space-before
	"leat" V <TH-Nom-Any> <mielde> <OR-Loc-HumGroup> <OR-eret-Plc> <dušše><TH-Inf> <árvvus> <LO-Loc-johtu><DE-Ill-Plc> <AT-Loc-Mat> <AT-Abe-Any> <AT-Nom-Any> <AT-Nom-Adj><EX-Ill-Ani> <PO-Loc-Hum> <PO-Gen-Hum> <MA-mielde-Any> <MA-Adv-Manner> <XT-Gen-Measr> <LO-maŋŋil-Time> <LO-Acc-Time> <LO-Loc-Time> <CO-Com-Ani> <ID-Nom-Any> <TH-Nom-Any><RO-Ess-Any><EX-Ill-Any> <EX-Ill-Ani><TH-Nom-Adj> <EX-Ill-Ani> <TH-Nom-Obj><RE-Ill-Ani> <LO-Loc-Any> <AktioEss> <BE-Ill-Ani><PU-Ess-Any> <RO-Ess-Any><PU-Ill-Act> <RO-Ess-Any> IV Ind Prs Sg3 <W:0.0> <doubleSpaceBefore> SUBSTITUTE:2764 SUBSTITUTE:2772 SUBSTITUTE:2979 SUBSTITUTE:3083 SUBSTITUTE:3121 SUBSTITUTE:3494 SUBSTITUTE:3593 SUBSTITUTE:3598 SUBSTITUTE:3605 SUBSTITUTE:3616 SUBSTITUTE:3704 SUBSTITUTE:3834 SUBSTITUTE:3845 SUBSTITUTE:3849 SUBSTITUTE:3999 SUBSTITUTE:4158 SUBSTITUTE:4169 SUBSTITUTE:4281 SUBSTITUTE:4286 SUBSTITUTE:4299 SUBSTITUTE:4306 SUBSTITUTE:4312 SUBSTITUTE:4539 SUBSTITUTE:4637 SUBSTITUTE:4698 SUBSTITUTE:4721 SUBSTITUTE:4727 SUBSTITUTE:4759 SUBSTITUTE:4875 @+FMAINV MAP:15822 "<diggereahkká lea>" &double-space-before &SUGGESTWF ID:2 R:$2:1 R:LEFT:1 ADD:4000:double-space-before COPY:4004:double-space-before
double-space-before
: 
"<gitta>"
	"gitta" Adv <W:0.0> @<ADVL MAP:22784
```

In LibreOffice it looks like the following:

<img width="446" alt="Skjermbilde 2019-08-14 kl  09 29 07" src="https://user-images.githubusercontent.com/1255285/62999136-2ce2f300-be76-11e9-9e0e-7ecd7c4880d1.png">

When applying the suggested correction, the result is the following:

<img width="478" alt="Skjermbilde 2019-08-14 kl  09 39 11" src="https://user-images.githubusercontent.com/1255285/62999549-77b13a80-be77-11e9-8962-4cc5e508b801.png">

The relevant CG rule is this (in the file `tools/grammarcheckers/grammarchecker-release.cg3`):

> `COPY:double-space-before ("<$2 $1>"v &SUGGESTWF) TARGET ("<(.*)>"r &double-space-before) IF (T:prevWordCrossSent LINK 0 ("<(.*)>"r)) (NOT 0 (&LINK)) ;`

The main problem is that there is no way for the regex to differentiate between the word form of the input, and the word forms given as suggestions by the speller; it seems that it randomly selects the second speller suggestion to be included in the grammar error suggestion. There should probably be a way of saying that one wants the first matching word form (which would be the input word form).

Also, for whatever reason, the blue underlining does not cover the whole error, which leads to a circular correction pattern, as the error persists (the two spaces are not replaced, only the following word), each time with the second speller suggestion as the "added" word.

**Comment by unhammer** [comment] 2019-12-06 13:45
Is this one fixed now, on the command line at least?

**Comment by snomos** [comment] 2019-12-10 13:52
It is fixed on the command line. I will keep it open until it is confirmed working properly in LO as well.

**Comment by unhammer** [comment] 2020-02-24 13:14
![bilde](https://user-images.githubusercontent.com/56868/75147476-b3b63980-56fd-11ea-8680-23178583a3b9.png)
![bilde](https://user-images.githubusercontent.com/56868/75147489-badd4780-56fd-11ea-8d64-9da12313f58a.png)

seems better?

**Comment by snomos** [comment] 2020-02-24 13:35
> seems better?

yes 👍 

But why is there an empty suggestion below the proper suggestion? And what happens if you select that one?

**Comment by unhammer** [comment] 2020-02-24 13:37
Removes the words :O seems like a bug in libreoffice-divvun

**Comment by unhammer** [comment] 2020-02-24 13:47
Actually, that seems to be because of the VSTR thing I just fixed in grammarchecker-release.cg3, should be ok again in newest svn of giella-sme.

(Managed to reproduce on linux too with yesterday's giella-sme vs manually built one.)

**Comment by unhammer** [comment] 2024-03-13 13:50
seems like we fixed this one

**Closed by unhammer** 2024-03-13 13:50 UTC
Labels: bug
